[global]
pprof = ":6061"
# data center id
dc = "dc1"

[log]
level = "info"

[nats]
url = "nats://172.29.0.1:4222"

[node]
# node id
nid = "islb01"

[redis]
addrs = ["chat.bots.im:6379"]
password = "68198226"
db = 0
