#!/bin/bash
#set -eux

TOP_DIR=$(cd `dirname $0`/../..; pwd)
CFG_DIR="${TOP_DIR}/examples/configs"
LOG_DIR="${TOP_DIR}/examples/logs"

ACTION=$1
SERVICE=$2

mkdir -p ${LOG_DIR}

show_help()
{
    echo ""
    echo "Usage: ./service {start|stop} {app-biz|signal|islb|sfu|avp}"
    echo ""
}

if [[ $# -ne 2 ]] ; then
    show_help
    exit 1
fi

function start()
{
    COMMAND=${TOP_DIR}/bin/$1
    CONFIG=${CFG_DIR}/$SERVICE.toml
    PID_FILE=${CFG_DIR}/$SERVICE.pid
    LOG_FILE=${LOG_DIR}/$SERVICE.log

    count=`ps -ef |grep " $COMMAND " |grep -v "grep" |wc -l`
    if [ 0 != $count ];then
        ps aux | grep " $COMMAND " | grep -v "grep"
        echo "already start"
        exit 1;
    fi

    if [ ! -r $CONFIG ]; then
        echo "$CONFIG does not exist"
        exit 1;
    fi

    if [[ ! -f $COMMAND ]]; then
        echo "$COMMAND does not exist."
        exit 1
    fi

    echo "nohup $COMMAND -c $CONFIG > $LOG_FILE 2>&1 &"
    nohup $COMMAND -c $CONFIG >$LOG_FILE 2>&1 &
    pid=$!
    echo "$pid" > $PID_FILE
    rpid=`ps aux | grep $pid |grep -v "grep" | awk '{print $2}'`
    if [[ $pid != $rpid ]];then
        echo "start failly."
        rm  $PID_FILE
        exit 1
    fi
}

function stop()
{
    PID_FILE=${CFG_DIR}/$1.pid
    echo "$PID_FILE......"

    echo "stop $SERVICE..."
    PID=`cat $PID_FILE`
    if [ ! -n "$PID" ]; then
        PID=`ps -ef | grep "$1" | grep -v "grep" | grep -v "service" | awk '{print $2}'`
        if [ ! -n "$PID" ]; then
            exit 1
        fi
    fi
    SUB_PIDS=`pgrep -P $PID`
    if [ -n "$SUB_PIDS" ]; then
        GRANDSON_PIDS=`pgrep -P $SUB_PIDS`
    fi

    # echo "kill $PID $SUB_PIDS $GRANDSON_PIDS"
    kill $PID $SUB_PIDS $GRANDSON_PIDS
    rm -rf $PID_FILE
    echo "stop ok"
}

if [[ "$ACTION" != "start" && "$ACTION" != "stop" ]]; then
    show_help
    exit 1
fi

if [[ "$SERVICE" != "app-biz" && "$SERVICE" != "signal" && "$SERVICE" != "islb" && "$SERVICE" != "sfu" && "$SERVICE" != "avp" ]]; then
    show_help
    exit 1
fi

if [[ "$ACTION" == "start" ]]; then
    start $SERVICE
    exit 0
fi

if [[ "$ACTION" == "stop" ]]; then
    stop $SERVICE
    exit 0
fi
