#!/bin/bash

function ufw_add() {
    ufw allow 4222
    ufw allow 6379
    ufw allow 5000/udp
    ufw allow 3478
    ufw allow 5551
    ufw allow 15000:15200/udp
}

function ufw_delete() {
    ufw delete allow 4222
    ufw delete allow 6379
    ufw delete allow 5000/udp
    ufw delete allow 3478
    ufw delete allow 5551
    ufw delete allow 15000:15200/udp
}

if [[ "$1" == "add" ]]; then 
    ufw_add
elif [[ "$1" == "delete" ]]; then
    ufw_delete
else
    echo "An ufw helper script."
    echo "usage: ufw add/delete"
fi
